### ISSUE TITLE
Latest build (4.0.0) contains syntax error

### ISSUE THREAD

**Issue by JeffreyArts** [klei/gulp-inject#172] opened 2016-03-21 09:26 UTC
```
node_modules/gulp-inject/src/inject/index.js:127
      startTag,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by joakimbeng** [comment] 2016-03-21 09:43
Duplicate of #171 

You're on an old NodeJS version...

**Closed by joakimbeng** 2016-03-21 09:43 UTC
