### ISSUE TITLE
Issue with task runner explorer

### ISSUE THREAD

**Issue by ashishrajput** [klei/gulp-inject#182] opened 2016-05-07 14:56 UTC
Visual Studio tool is not able to manage the json object.

This is in the file

```
D:\projects\leaderboard\ViperWebApplication\Viper.WebRegistration.Web\node_modules\gulp-inject\src\inject\index.js:127
      startTag,
```

It's supposing startTag a key and looking for its value.

```
{
      startTag,
      endTag,
      tagsToInject : [],
      removeTags: opt.removeTags,
      onMatch(match) {
        matches.push(match[0]);
      }
    }
```
For detailed error please look into the log
```
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\projects\leaderboard\ViperWebApplication\Viper.WebRegistration.Web\node_modules\gulp-inject\index.js:4:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
D:\projects\leaderboard\ViperWebApplication\Viper.WebRegistration.Web\node_modules\gulp-inject\src\inject\index.js:127
      startTag,
```

**Comment by joakimbeng** [comment] 2016-05-18 06:12
Duplicate of #171

**Closed by joakimbeng** 2016-05-18 06:12 UTC
