### ISSUE TITLE
Inject doesn’t remove deleted files from the html if there’s no one left

### ISSUE THREAD

**Issue by zhekaus** [klei/gulp-inject#128] opened 2015-08-10 19:30 UTC
For instance, If I remove all the css files injected, angular-inject lives them in an html file. However, if I add one, inject perfectly refreshes the file list in an html file.

**Comment by sergesemashko** [comment] 2015-09-03 19:21
+1, have the same issue. Still have one file injected when there are no files in the stream. Content between inject tags is getting updated if stream is empty.

**Comment by LouisTakePILLz** [comment] 2015-09-13 18:34
Experiencing the same issue here.

**Comment by joakimbeng** [comment] 2015-09-14 17:31
Duplicate of #59

**Closed by joakimbeng** 2015-09-14 17:31 UTC
